apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - command:
    - sh
    - -c
    - ping google.com
    image: bash
    name: bash
    resources: {}
  - name: proxy
    command:
    - sh
    - -c
    - apt-get update && apt-get install iptables -y && iptables -L && sleep 1d
    image: ubuntu
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
