apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secure
  name: secure
spec:
  containers:
  - image: nginx
    name: secure
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profile-docker-nginx.json
status: {}
