apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  groups:
  - system:authenticated
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ21UQ0NBWUVDQVFBd1ZERUxNQWtHQTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeApJVEFmQmdOVkJBb01HRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpERU5NQXNHQTFVRUF3d0VhbUZ1ClpUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUwyQlN5bXVFM3d0b1lpaGNYQnAKRG1HZHpBODRrR1d3RG1sMVQzVnVJN21EZUFOT0didnhteTQrR1J5dlI0YXFiUTJXNDJ4TUkwWUZXL0JRSGFSRgoxN25UNFJMSjJFaTkxcjRsSWtLdDNVcXhNb21oaXROQ0pGaHlNTlc3ZTEwZVlXMGdvc1RqaUxtcUt4bm1lcWlBCjJHbHEvekZzKzNPT1JVcEljYmFGbXN0Z0RlUVgxSjY3NUlFU3hycDNMUHFoMk5SdzRCTG5ySThUbWRGVUlKSGsKZlNyVnRVZm11cnVtcnFQeXgrZmdUalgwa2NtMyt5VS9PQkI0QzhLOHJvQ1hicFpxOExmMVJLWjlhOHVJZWpFKwpjSjRUQmFHb2hXSko2YWxOT1hEL0tPd0xQT3h2TlkxUFFEZy9VQ2g0V0pEV2FpYkFpVXZxY1Z1VXhTSU5HMTNKCmczOENBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlR6cU4xQWV5eTVycDBuTC9kaFMzMUNXV1UKb29uZnU4dkxINHRKdm1QVFFmeDYwaytub2wzcmlVSDdKUWRGMzJueVFUaVlDR204bzhlVGJPOUc5T3h2L1UxSApGbEdGNWxjQmwwMUVrVnl2bzh0bnNSY0tKQW4xdHNkMlBWdjlLSm1JbGZYWjFRRktmajRocTNuTlg5U1JsY0Z6CnBQUzBWUi9iWVJteEIvN21MR3R6UlF4M3FjekptWDZ2WkNuR1RQNGpFcWFvczJEQ1BWK08rWE1rcENBWW9pMXMKZWM3M0JRL25DVTVDODQ3QUQ0dmRlY1NHU1BydW1wdlFIMGk5QUJSMm4zemliR0FSTVUycExnNVNhWlBWZXlPagpJbE9zTHpnajlUbGFhRGo3YVI4SjNxSEUvL0haL29hNXU0U3hoSWtCeUxiTmdHZHpRRDYvUmRyRlpIcksKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # one day
  usages:
    - client auth
