apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: assessor-pod
  name: assessor-pod
spec:
  serviceAccountName: assessor
  containers:
  - image: bitnami/kubectl
    name: assessor-pod
    resources: {}
    command: ["/bin/bash"]
    args: ["-c", "while true; do sleep 3600; done"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
