apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-file-system
  name: pod-file-system
spec:
  containers:
  - image: nginx
    name: pod-file-system
    resources: {}
    volumeMounts:
        # name must match the volume name below
        - name: secret1
          mountPath: /etc/secret1
          readOnly: true
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret1
      secret:
        secretName: secret1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
