apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  ports:
  - name: 80-80
    nodePort: 30950
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: pod-file-system
  type: NodePort
status:
  loadBalancer: {}
